# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://nbekenov.com/
baseurl: '/'
title: Nathan Bekenov
author: Nathan Bekenov
description: Personal blog and resume
avatar: profile.png
email: n.bekenov01@gmail.com
github: nbekenov # username
twitter: nathanbekenov
linkedin: nathanbekenov
# stackoverflow: username   #e.g: users/2735833/proton1h1
medium: nursultanbekenov #e.g: NobelPeaceOslo
#Comment out if you don't want disqus
# disqus: username
# google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
